fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    archive: 'https://github.com/nanliu/puppet-archive.git'
    staging: 'https://github.com/nanliu/puppet-staging.git'
    java: 'https://github.com/bodeco/puppet-java.git'
    helper: 'https://github.com/bodeco/bodeco_module_helper.git'
    pe_gem:
      repo: https://github.com/puppetlabs/puppetlabs-pe_gem.git
      ref: 0.1.0
    powershell: https://github.com/puppetlabs/puppetlabs-powershell.git
  symlinks:
    gocd: "#{source_dir}"